-- Your SQL goes here
CREATE TABLE IF NOT EXISTS tproject (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(64) NOT NULL,
  owner varchar(64) NOT NULL,
  default_lang varchar(8) DEFAULT 'en' NOT NULL
);

CREATE TABLE IF NOT EXISTS tgroup (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(128) NOT NULL,
  project integer REFERENCES tproject (id) ON DELETE CASCADE NOT NULL,
  UNIQUE (name, project)
);

CREATE TABLE IF NOT EXISTS translation (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id integer REFERENCES tgroup (id)  ON DELETE CASCADE NOT NULL,
  lang varchar(16) NOT NULL,
  key varchar(48) NOT NULL,
  translated text,
  UNIQUE (group_id, lang, key)
);
